# Generated by Django 4.2.7 on 2025-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('travel', 'Travel'), ('other', 'Other')], default='other', help_text='Category of the recurring expense', max_length=50),
        ),
    ]
